use dblec;
insert into players (first_name ,last_name,team_id) values("幸太郎","内川",4);
insert into players (first_name ,last_name,team_id) values("紗佳","岡田",4);
insert into players (first_name ,last_name,team_id) values("誠","沢崎",4);
insert into players (first_name ,last_name,team_id) values("隆晴","多井",5);
insert into players (first_name ,last_name,team_id) values("翔","白鳥",5);
insert into players (first_name ,last_name,team_id) values("吉弘","松本",5);
insert into players (first_name ,last_name,team_id) values("藍子","日向",5);
insert into players (first_name ,last_name,team_id) values("聖人","萩原",6);
insert into players (first_name ,last_name,team_id) values("直樹","瀬戸熊",6);
insert into players (first_name ,last_name,team_id) values("咲","黒沢",6);
insert into players (first_name ,last_name,team_id) values("剛","小林",7);
insert into players (first_name ,last_name,team_id) values("康心","朝倉",7);
insert into players (first_name ,last_name,team_id) values("伸洋","石橋",7);
insert into players (first_name ,last_name,team_id) values("明奈","瑞原",7);
insert into players (first_name ,last_name,team_id) values("寿人","佐々木",8);
insert into players (first_name ,last_name,team_id) values("まり","高宮",8);
insert into players (first_name ,last_name,team_id) values("雄大","前原",8);
insert into players (first_name ,last_name,team_id) values("智","藤崎",8);
select players.last_name, players.first_name, teams.name  from players join teams on players.team_id = teams.id;